name: Ubuntu
on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**/man/*'
      - '**.md'
      - '**.rdoc'
      - '**/.document'
      - '.*.yml'
  pull_request:
    # Do not use paths-ignore for required status checks
    # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
  merge_group:

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

permissions:
  contents: read

jobs:
  make:
    env:
      GITPULLOPTIONS: --no-tags origin ${{ github.ref }}
      RUBY_DEBUG: ci
      ASAN_OPTIONS=detect_leaks: 1
      RUBY_FREE_AT_EXIT: 1

    runs-on: ubuntu-latest

    if: >-
      ${{!(false
      || contains(github.event.head_commit.message, '[DOC]')
      || contains(github.event.head_commit.message, 'Document')
      || contains(github.event.pull_request.title, '[DOC]')
      || contains(github.event.pull_request.title, 'Document')
      || contains(github.event.pull_request.labels.*.name, 'Documentation')
      || (github.event_name == 'push' && github.event.pull_request.user.login == 'dependabot[bot]')
      )}}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: /.github

      - uses: ./.github/actions/setup/ubuntu

      - uses: ruby/setup-ruby@d8d83c3960843afb664e821fed6be52f37da5267 # v1.231.0
        with:
          ruby-version: '3.1'
          bundler: none

      - uses: ./.github/actions/setup/directories
        with:
          srcdir: src
          builddir: build
          makeup: true
          clean: true
          dummy-files: true
          # Set fetch-depth: 10 so that Launchable can receive commits information.
          fetch-depth: 10

      - name: Run configure
        run: >-
          $SETARCH ../src/configure -C --disable-install-doc cflags='-fsanitize=address -fno-omit-frame-pointer'

      - run: $SETARCH make

      - run: $SETARCH make hello

      - name: Set up Launchable
        id: launchable
        uses: ./.github/actions/launchable/setup
        with:
          os: ubuntu-latest
          test-opts: cflags='-fsanitize=address -fno-omit-frame-pointer'
          launchable-token: ${{ secrets.LAUNCHABLE_TOKEN }}
          builddir: build
          srcdir: src
        continue-on-error: true
        timeout-minutes: 3

      - name: make check
        run: |
          test -n "${LAUNCHABLE_STDOUT}" && exec 1> >(tee "${LAUNCHABLE_STDOUT}")
          test -n "${LAUNCHABLE_STDERR}" && exec 2> >(tee "${LAUNCHABLE_STDERR}")

          $SETARCH make -s check
        timeout-minutes: 40
        env:
          RUBY_TESTOPTS: '-q --tty=no'
          LAUNCHABLE_STDOUT: ${{ steps.launchable.outputs.stdout_report_path }}
          LAUNCHABLE_STDERR: ${{ steps.launchable.outputs.stderr_report_path }}

      - uses: ./.github/actions/slack
        with:
          label: ASAN
          SLACK_WEBHOOK_URL: ${{ secrets.SIMPLER_ALERTS_URL }} # ruby-lang slack: ruby/simpler-alerts-bot
        if: ${{ failure() }}

  result:
    if: ${{ always() }}
    name: ${{ github.workflow }} result
    runs-on: ubuntu-latest
    needs: [make]
    steps:
      - run: exit 1
        working-directory:
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}

defaults:
  run:
    working-directory: build
